apiVersion: apps/v1
kind: Deployment
metadata:
  name: spendwise-fo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spendwise-fo
  template:
    metadata:
      labels:
        app: spendwise-fo
    spec:
      containers:
        - name: spendwise-fo
          image: kavindudocker/spendwise-fo:latest
          ports:
            - containerPort: 80