apiVersion: v1
kind: Service
metadata:
  name: spendwise-fo-service
spec:
  selector:
    app: spendwise-fo
  ports:
    - protocol: TCP
      port: 80  # The external port for your service
      targetPort: 80  # The port on which your app is running in the container
  type: LoadBalancer  # Use NodePort or ClusterIP for local clusters